Marker-Inc-Korea/RAGchain

requirements.txt, run_localGPT.py
=> add repeat penalty to use RepetitionPenalty & NoRepeatNGram

README.md
need to work more with examples
=> unfinished korean README

.gitignore, README.md, run_localGPT.py
close #28
[Huggingface](https://huggingface.co/vkehfdl1/KuLLM-Polyglot-12.8b-v2-ggml) for KuLLM ggml 5-bit model.
=> change KuLLM model to our own ggml

ingest.py
하위 디렉토리에 있는 모든 파일들을 ingest 가능!
=> done search for all files in root directory for ingest documents

evaluate/strategyQA/README.md, evaluate/strategyQA/evaluate.py
=> Hot fix/#70

KoPrivateGPT/DB/mongo_db.py, KoPrivateGPT/DB/pickle_db.py, KoPrivateGPT/pipeline/__init__.py, KoPrivateGPT/pipeline/basic.py, KoPrivateGPT/pipeline/selector.py, KoPrivateGPT/retrieval/vectordb_retrieval.py, KoPrivateGPT/utils/__init__.py, KoPrivateGPT/utils/embed/__init__.py, KoPrivateGPT/utils/embed/embeddingfactory.py, KoPrivateGPT/utils/util.py, KoPrivateGPT/utils/vectorDB/pinecone.py, app.py, evaluate/strategyQA/ingest.py, evaluate/strategyQA/pred.py, ingest.py, run_localGPT.py
=> Refactor Embedding utils

requirements.txt
close #138 
Sorry my branch name was incorrect lol
=> delete not using libraries

KoPrivateGPT/benchmark/retrieval/metrics.py, KoPrivateGPT/llm/basic.py, KoPrivateGPT/llm/rerank.py, KoPrivateGPT/llm/visconde.py, KoPrivateGPT/pipeline/selector.py, KoPrivateGPT/retrieval/__init__.py, KoPrivateGPT/retrieval/hyde.py, KoPrivateGPT/utils/__init__.py, KoPrivateGPT/utils/query_decompose.py, KoPrivateGPT/utils/reranker/llm/llm.py, KoPrivateGPT/utils/util.py, run_localGPT.py, tests/KoPrivateGPT/DB/test_base_db.py, tests/KoPrivateGPT/DB/test_mongo_db.py, tests/KoPrivateGPT/DB/test_pickle_db.py, tests/KoPrivateGPT/pipeline/test_basic_pipeline.py, tests/KoPrivateGPT/pipeline/test_selector.py, tests/KoPrivateGPT/retrieval/test_base_retrieval.py, tests/KoPrivateGPT/retrieval/test_bm25_retrieval.py, tests/KoPrivateGPT/retrieval/test_hyde_retrieval.py, tests/KoPrivateGPT/utils/reranker/test_mono_t5_reranker.py
new HyDE module and fix some errors at test.
=> new HyDE module

KoPrivateGPT/llm/visconde.py, KoPrivateGPT/utils/__init__.py, setup.py, tests/README.md
=> Hot fix/#164

.gitignore, setup.py
=> modify setup.py

KoPrivateGPT/DB/pickle_db.py, KoPrivateGPT/llm/basic.py, KoPrivateGPT/llm/rerank.py, KoPrivateGPT/llm/visconde.py, KoPrivateGPT/pipeline/basic.py, KoPrivateGPT/pipeline/selector.py, KoPrivateGPT/retrieval/hyde.py, KoPrivateGPT/retrieval/vectordb_retrieval.py, KoPrivateGPT/utils/__init__.py, KoPrivateGPT/utils/embed/embeddingfactory.py, KoPrivateGPT/utils/evidence_extractor.py, KoPrivateGPT/utils/query_decompose.py, KoPrivateGPT/utils/reranker/llm/llm.py, tests/KoPrivateGPT/retrieval/test_hyde_retrieval.py, tests/KoPrivateGPT/utils/test_evidence_extractor.py, tests/KoPrivateGPT/utils/test_query_decompose.py
close #147
- create evidence extractor which can highlight given passage
- empty __init__.py at utils module due to circular import errors
- make query decompose test file
- make model_kwargs at HydeRetrieval
- shorten time of testing HyDERetrieval
=> evidence extractor

KoPrivateGPT/pipeline/selector.py, KoPrivateGPT/preprocess/loader/file_loader.py, KoPrivateGPT/preprocess/loader/pdf_link_loader.py, tests/KoPrivateGPT/preprocess/loader/test_pdf_link_loader.py
=> add pdf link loader

KoPrivateGPT/utils/reranker/pygaggle/transformer.py
=> add legacy=False for removing warning about monoT5Reranker

KoPrivateGPT/utils/embed/embeddingfactory.py, tests/KoPrivateGPT/utils/embed/test_embeddingfactory.py
=> add multilingual-e5 model to embeddingfactory.py

KoPrivateGPT/preprocess/loader/hwp_loader.py
=> retry connection at hwp loader

KoPrivateGPT/llm/base.py, KoPrivateGPT/llm/basic.py, KoPrivateGPT/llm/rerank.py, KoPrivateGPT/llm/visconde.py, tests/KoPrivateGPT/llm/test_basic_llm.py, tests/KoPrivateGPT/llm/test_visconde_llm.py
=> stream feature

KoPrivateGPT/retrieval/__init__.py, KoPrivateGPT/retrieval/base.py, KoPrivateGPT/retrieval/bm25_retrieval.py, KoPrivateGPT/retrieval/hybrid.py, KoPrivateGPT/retrieval/hyde.py, KoPrivateGPT/retrieval/vectordb_retrieval.py, tests/KoPrivateGPT/retrieval/test_bm25_retrieval.py, tests/KoPrivateGPT/retrieval/test_hybrid_retrieval.py, tests/KoPrivateGPT/retrieval/test_hyde_retrieval.py, tests/KoPrivateGPT/retrieval/test_vectordb_retrieval.py
=> Hybrid Retrieval

KoPrivateGPT/retrieval/hybrid.py, tests/KoPrivateGPT/retrieval/test_hybrid_retrieval.py
=> fix error and test if at test

KoPrivateGPT/retrieval/hybrid.py
=> concurrent processing at hybrid retrieval

KoPrivateGPT/llm/base.py, KoPrivateGPT/llm/basic.py, KoPrivateGPT/llm/visconde.py
For openai api model options
close #199
=> add *args, **kwargs to all ask function at llm classes

KoPrivateGPT/llm/base.py
=> add len check at generate_chat stream

KoPrivateGPT/llm/base.py
=> notify end of stream

KoPrivateGPT/retrieval/hybrid.py, tests/KoPrivateGPT/retrieval/test_hybrid_retrieval.py
=> RRF algorithm at hybrid retrieval

KoPrivateGPT/utils/embed/embeddingfactory.py, tests/KoPrivateGPT/utils/embed/test_embeddingfactory.py
close #224 
You can use sentence embedding with HuggingfaceEmbedding easily. 
Contriever model use mean pooling, and Huggingface automatically use mean pooling. 
Just use langchain Huggingface Embeddings for contriever.
=> add contriever to embeddingfactory

KoPrivateGPT/reranker/llm/llm.py, KoPrivateGPT/reranker/pygaggle/monoT5.py, KoPrivateGPT/reranker/tart/tart.py
=> add KoPrivateGPT at import path

KoPrivateGPT/DB/base.py, KoPrivateGPT/DB/mongo_db.py, KoPrivateGPT/DB/pickle_db.py, KoPrivateGPT/retrieval/base.py, KoPrivateGPT/utils/file_cache.py, tests/KoPrivateGPT/DB/test_base_db.py, tests/KoPrivateGPT/DB/test_mongo_db.py, tests/KoPrivateGPT/DB/test_pickle_db.py, tests/KoPrivateGPT/retrieval/test_base_retrieval.py, tests/KoPrivateGPT/retrieval/test_bm25_retrieval.py, tests/KoPrivateGPT/retrieval/test_vectordb_retrieval.py
=> db search with filters

tests/conftest.py
=> add conftest.py and flush redis db when session is finished.

KoPrivateGPT/utils/vectorstore/pinecone.py, requirements.txt, tests/KoPrivateGPT/utils/vectorstore/test_pinecone.py
=> Update langchain to 0.0.307

RAGchain/pipeline/basic.py, RAGchain/utils/embed/embeddingfactory.py, RAGchain/utils/linker/redisdbSingleton.py, RAGchain/utils/util.py
=> delete load_dotenv() function at library files

setup.py
=> add long_description from README.md at setup.py

RAGchain/preprocess/text_splitter/code_splitter.py, RAGchain/preprocess/text_splitter/html_header_splitter.py, RAGchain/preprocess/text_splitter/markdown_header_splitter.py, RAGchain/preprocess/text_splitter/token_splitter.py, tests/RAGchain/preprocess/text_splitter/test_token_splitter.py
close #295.
Remove inaccurate annotation.
=> Remove inaccurate annotation.

RAGchain/benchmark/dataset/qasper.py, tests/RAGchain/benchmark/dataset/test_qasper.py
=> add random_state option at qasper evaluator for constant benchmarking

RAGchain/retrieval/vectordb_retrieval.py, setup.py
=> version update and fix langchain VectorStore location for proper use

RAGchain/benchmark/dataset/qasper.py, tests/RAGchain/benchmark/dataset/test_qasper.py
=> Hot fix/#303

RAGchain/benchmark/dataset/__init__.py, RAGchain/benchmark/dataset/base.py, RAGchain/benchmark/dataset/msmarco.py, tests/RAGchain/benchmark/dataset/test_msmarco.py
I create msmarco dataset evaluation code and test code. It uses metrics of BLEU and ROUGE-L.
close #299
=> Create msmarco dataset evaluation code and test code.

RAGchain/benchmark/dataset/msmarco.py, tests/RAGchain/benchmark/dataset/test_msmarco.py
=> Add code version optional and change msmarco test data to train data.

setup.py
=> langchain and chromadb version update

RAGchain/benchmark/answer/metrics.py, RAGchain/benchmark/auto.py, RAGchain/benchmark/base.py, RAGchain/benchmark/dataset/ko_strategy_qa.py, RAGchain/benchmark/dataset/msmarco.py, RAGchain/benchmark/dataset/qasper.py, RAGchain/benchmark/dataset/strategy_qa.py, setup.py, tests/RAGchain/benchmark/answer/test_answer_metrics.py, tests/RAGchain/benchmark/dataset/test_ko_strategy_qa.py, tests/RAGchain/benchmark/dataset/test_msmarco.py, tests/RAGchain/benchmark/dataset/test_qasper.py, tests/RAGchain/benchmark/dataset/test_startegy_qa.py, tests/RAGchain/benchmark/test_auto.py, tests/RAGchain/benchmark/test_base.py
- Now we have BLEU score (answer evaluation with ground truths)
- You can see ground truth values at EvaluateResult.each_results
- We classify each metrics easily make using_metrics and its child classes.
- change answer metric solution input for multiple ground truth values.
=> Add BLEU score + refactor __calculate_metrics

RAGchain/benchmark/base.py, tests/RAGchain/benchmark/test_base.py
Add test code for without ragas evaluator
close #305
=> import ragas when ragas metrics are used.

RAGchain/benchmark/base.py
=> Fix error at retrieval gt calculation

RAGchain/benchmark/dataset/__init__.py, RAGchain/benchmark/dataset/mr_tydi.py, tests/RAGchain/benchmark/dataset/test_mr_tydi.py
Create Mr.tydi benchmark and test code.
close #310.
=> Create Mr.tydi benchmark and test code.

RAGchain/pipeline/visconde.py, tests/RAGchain/pipeline/test_visconde_pipeline.py
=> fix missing parameter at default QueryDecomposition

RAGchain/benchmark/dataset/mr_tydi.py
=> Modify mr_tydi.py some else cases.

RAGchain/benchmark/auto.py, RAGchain/benchmark/base.py, RAGchain/benchmark/dataset/msmarco.py, RAGchain/benchmark/dataset/qasper.py, tests/RAGchain/benchmark/dataset/test_msmarco.py
=> Add answer gt at msmarco.py.

RAGchain/benchmark/dataset/__init__.py, RAGchain/benchmark/dataset/nfcorpus.py, setup.py, tests/RAGchain/benchmark/dataset/test_nfcorpus.py
=> Create nfcorpus benchmark

RAGchain/DB/pickle_db.py, tests/RAGchain/retrieval/test_hybrid_retrieval.py, tests/RAGchain/retrieval/test_vectordb_retrieval.py
close #316
@bwook00 You can check only pickle_db.py
=> Fix PickleDB and test files for passing pytest at full run of test files.

RAGchain/benchmark/dataset/__init__.py, RAGchain/benchmark/dataset/asqa.py, tests/RAGchain/benchmark/dataset/test_asqa.py
=> Create ASQA benchmark

RAGchain/retrieval/base.py, tests/RAGchain/retrieval/test_base_retrieval.py, tests/RAGchain/retrieval/test_bm25_retrieval.py, tests/RAGchain/retrieval/test_vectordb_retrieval.py
=> Feature/#385 & Feature/#382

RAGchain/reranker/time/__init__.py, RAGchain/reranker/time/simple_time.py, tests/RAGchain/reranker/test_simple_time_reranker.py
=> Make SimpleTimeReranker

RAGchain/benchmark/answer/metrics.py, RAGchain/benchmark/base.py, setup.py, tests/RAGchain/benchmark/answer/test_answer_metrics.py
Now we have METEOR score (answer evaluation with ground truths)
change answer metric solution input for multiple ground truth values.
our function will calculate max of METEOR scores between each gt values and answer
[METEOR – Wikipedia](https://en.wikipedia.org/wiki/METEOR)
[METEOR score – NLTK](https://www.nltk.org/_modules/nltk/translate/meteor_score.html)
=> add METEOR answer metric

RAGchain/benchmark/answer/metrics.py, RAGchain/benchmark/base.py, setup.py, tests/RAGchain/benchmark/answer/test_answer_metrics.py
Now we have ROUGE score (answer evaluation with ground truths)
change answer metric solution input for multiple ground truth values.
our function will calculate max of ROUGE scores between each gt values and answer
[ROUGE - github](https://github.com/google-research/google-research/tree/master/rouge)
[ROUGE score - Wikipedia](https://en.wikipedia.org/wiki/ROUGE_(metric))
=> add ROUGE answer metric

RAGchain/schema/passage.py, RAGchain/utils/compressor/__init__.py, RAGchain/utils/compressor/base.py, RAGchain/utils/compressor/cluster_time.py, RAGchain/utils/semantic_clustering.py, tests/RAGchain/utils/compressor/test_cluster_time_compressor.py, tests/RAGchain/utils/test_semantic_clustering.py
close #390
I made semantic clustering, that embeds each passage and semantically cluster that.
Plus, I made ClusterTimeCompressor, which cluster each passages and remain only latest passage in each semantic cluster.
This is one of solution of time-aware RAG.
=> make semantic clustering and time compressor using semantic clustering

RAGchain/reranker/time/__init__.py, RAGchain/reranker/time/simple_time.py, RAGchain/reranker/time/weighted_time.py, tests/RAGchain/reranker/test_simple_time_reranker.py, tests/RAGchain/reranker/test_weighted_time_reranker.py
=> add WeightedTimeReranker

RAGchain/__init__.py, RAGchain/utils/linker/json_linker.py
=> [Hotfix]Add jsonLinker selector + change class name in code comment

RAGchain/reranker/importance/__init__.py, RAGchain/reranker/importance/simple_importance.py, RAGchain/reranker/importance/weighted_importance.py, README.md, tests/RAGchain/reranker/test_simple_importance_reranker.py, tests/RAGchain/reranker/test_weighted_importance_reranker.py
=> make SimpleImportanceReranker & WeightedImportanceReranker

RAGchain/utils/compressor/llm_lingua.py, setup.py, tests/RAGchain/utils/compressor/test_llm_lingua_compressor.py
It can use with any LCEL functions.
=> Create LLMLinguaCompressor for prompt compression

RAGchain/reranker/time/weighted_time.py, tests/RAGchain/reranker/test_weighted_importance_reranker.py, tests/RAGchain/reranker/test_weighted_time_reranker.py
=> Fix error at WeightedTimeReranker

RAGchain/__init__.py, RAGchain/pipeline/google_search.py, RAGchain/utils/linker/dynamo_linker.py, RAGchain/utils/linker/redis_linker.py, tests/RAGchain/utils/vectorstore/test_pinecone.py
=> delete all load_dotenv in the project

RAGchain/benchmark/answer/metrics.py, RAGchain/benchmark/base.py, RAGchain/benchmark/retrieval/evaluator.py, RAGchain/benchmark/retrieval/metrics.py, tests/RAGchain/benchmark/answer/test_answer_metrics.py, tests/RAGchain/benchmark/retrieval/test_metrics.py, tests/RAGchain/benchmark/test_base.py
=> [HotFix] EM name duplicated with retrieval_gt and answer_gt 

RAGchain/utils/linker/json_linker.py
close #451
@bwook00 
이거보세요~~~~
=> HotFix json linker fatal bug
